const s = {
  wrapper: { maxWidth: "1100px", margin: "0 auto", padding: "0.75rem 0.75rem 3rem" },
  outerCard: {
    background: "#fff",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
    padding: "1rem 1.25rem 1.25rem",
    marginBottom: "0.75rem",
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
  },
  sectionTitle: {
    fontFamily: "'Georgia', serif",
    fontStyle: "italic",
    fontSize: "0.95rem",
    color: "#ea580c",
    fontWeight: "600",
    marginBottom: "0.75rem",
  },
  label: {
    display: "block",
    marginBottom: "0.25rem",
    fontWeight: "600",
    color: "#1e293b",
    fontSize: "0.8rem",
  },
  input: {
    width: "100%",
    padding: "0.55rem 0.75rem",
    borderRadius: "8px",
    border: "1.5px solid #e2e8f0",
    background: "#fff",
    fontSize: "0.875rem",
    outline: "none",
    boxSizing: "border-box",
    height: "40px",
    fontFamily: "'Inter', system-ui, sans-serif",
  },
  textarea: {
    width: "100%",
    padding: "0.55rem 0.75rem",
    borderRadius: "8px",
    border: "1.5px solid #e2e8f0",
    background: "#fff",
    fontSize: "0.875rem",
    resize: "none",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "'Inter', system-ui, sans-serif",
  },
  submitBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.4rem",
    width: "100%",
    maxWidth: "280px",
    margin: "0.75rem auto 0",
    padding: "0 1.25rem",
    height: "36px",
    background: "#ea580c",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "0.85rem",
    cursor: "pointer",
    textAlign: "center",
    transition: "all 0.15s ease",
    fontFamily: "'Inter', system-ui, sans-serif",
  },
  uploadZone: {
    border: "2px dashed #fed7aa",
    background: "#fff7ed",
    borderRadius: "10px",
    padding: "1.5rem 1.25rem",
    textAlign: "center",
    cursor: "pointer",
    maxHeight: "120px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.35rem",
    transition: "all 0.15s ease",
  },
  attachBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4rem",
    padding: "0.35rem 0.85rem",
    background: "linear-gradient(135deg, #fef3c7 0%, #ffedd5 100%)",
    color: "#b45309",
    borderRadius: "6px",
    textDecoration: "none",
    fontSize: "0.78rem",
    fontWeight: "600",
    border: "1px solid #fcd34d",
    marginTop: "0.5rem",
  },
  batchBadge: (active) => ({
    display: "inline-block",
    padding: "0.25rem 0.85rem",
    borderRadius: "6px",
    fontWeight: "600",
    fontSize: "0.78rem",
    cursor: "pointer",
    border: "none",
    background: active ? "#ea580c" : "#fff7ed",
    color: active ? "#fff" : "#ea580c",
    transition: "all 0.15s",
  }),
  folderCard: {
    background: "#fff",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    padding: "1rem",
    textAlign: "center",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    cursor: "pointer",
    transition: "all 0.15s",
  },
  deleteBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "28px",
    height: "28px",
    background: "transparent",
    color: "#ef4444",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "0.78rem",
    transition: "background 0.15s",
  },
  noticeCard: {
    background: "#fff",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    padding: "0.85rem 1rem",
    marginBottom: "0.5rem",
    boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  publishBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.35rem",
    padding: "0.3rem 0.85rem",
    background: "#ea580c",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    fontWeight: "600",
    fontSize: "0.78rem",
    cursor: "pointer",
    height: "32px",
    transition: "all 0.15s",
  },
  declineBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.35rem",
    padding: "0.3rem 0.85rem",
    background: "#fff",
    color: "#1e293b",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    fontWeight: "500",
    fontSize: "0.78rem",
    cursor: "pointer",
    height: "32px",
    transition: "all 0.15s",
  },
  profileCard: {
    background: "#f8fafc",
    padding: "1rem",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
  },
  profileLabel: {
    display: "block",
    fontSize: "0.7rem",
    color: "#94a3b8",
    marginBottom: "0.25rem",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  profileValue: { fontWeight: "700", color: "#1e293b", fontSize: "0.95rem" },
  feedbackToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.4rem",
    padding: "0.4rem 1rem",
    background: "#fff",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "0.82rem",
    cursor: "pointer",
    margin: "0 auto",
    height: "36px",
    transition: "all 0.15s",
  },
};

export default s;