export const s = {
  wrapper: { maxWidth: "900px", margin: "0 auto", padding: "1rem 1rem 4rem" },
  outerCard: {
    background: "#fff",
    borderRadius: "18px",
    border: "1px solid #ffe0cc",
    padding: "2rem 2rem 2.5rem",
    marginBottom: "2rem",
  },
  sectionTitle: {
    fontFamily: "'Georgia', serif",
    fontStyle: "italic",
    fontSize: "1.35rem",
    color: "#ea580c",
    fontWeight: "600",
    marginBottom: "1.5rem",
  },
  label: {
    display: "block",
    marginBottom: "0.4rem",
    fontWeight: "600",
    color: "#1e293b",
    fontSize: "0.9rem",
  },
  input: {
    width: "100%",
    padding: "0.85rem 1rem",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    background: "#f8fafc",
    fontSize: "0.95rem",
    outline: "none",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "0.85rem 1rem",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    background: "#f8fafc",
    fontSize: "0.95rem",
    resize: "none",
    outline: "none",
    boxSizing: "border-box",
  },
  submitBtn: {
    display: "block",
    width: "100%",
    maxWidth: "320px",
    margin: "1.5rem auto 0",
    padding: "0.85rem 2rem",
    background: "#ea580c",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    fontWeight: "700",
    fontSize: "0.95rem",
    cursor: "pointer",
    textAlign: "center",
  },
  uploadZone: {
    border: "2px dashed #fed7aa",
    background: "#fff7ed",
    borderRadius: "14px",
    padding: "3rem 2rem",
    textAlign: "center",
    cursor: "pointer",
  },
  attachBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.5rem 1.25rem",
    background: "linear-gradient(135deg, #fef3c7 0%, #ffedd5 100%)",
    color: "#b45309",
    borderRadius: "8px",
    textDecoration: "none",
    fontSize: "0.85rem",
    fontWeight: "600",
    border: "1px solid #fcd34d",
    marginTop: "0.75rem",
  },
  batchBadge: (active) => ({
    display: "inline-block",
    padding: "0.35rem 1.1rem",
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "0.85rem",
    cursor: "pointer",
    border: "none",
    background: active ? "#ea580c" : "#fff7ed",
    color: active ? "#fff" : "#ea580c",
    transition: "all 0.2s ease",
  }),
  folderCard: {
    background: "#fff",
    borderRadius: "14px",
    border: "1px solid #f1f5f9",
    padding: "1.5rem",
    textAlign: "center",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  deleteBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "28px",
    height: "28px",
    background: "transparent",
    color: "#ef4444",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "0.8rem",
  },
  noticeCard: {
    background: "#fff",
    borderRadius: "14px",
    border: "1px solid #f1f5f9",
    padding: "1.25rem 1.5rem",
    marginBottom: "1.25rem",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  publishBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4rem",
    padding: "0.45rem 1.2rem",
    background: "#ea580c",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "0.85rem",
    cursor: "pointer",
  },
  declineBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4rem",
    padding: "0.45rem 1.2rem",
    background: "#fff",
    color: "#1e293b",
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    fontWeight: "500",
    fontSize: "0.85rem",
    cursor: "pointer",
  },
  profileCard: {
    background: "#f8fafc",
    padding: "1.5rem",
    borderRadius: "14px",
    border: "1px solid #e2e8f0",
  },
  profileLabel: {
    display: "block",
    fontSize: "0.8rem",
    color: "#94a3b8",
    marginBottom: "0.4rem",
    fontWeight: "500",
  },
  profileValue: { fontWeight: "700", color: "#1e293b", fontSize: "1rem" },
  feedbackToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    padding: "0.6rem 1.5rem",
    background: "#fff",
    border: "1px solid #cbd5e1",
    borderRadius: "10px",
    fontWeight: "600",
    fontSize: "0.9rem",
    cursor: "pointer",
    margin: "0 auto",
  },
};

export default s;